# Generated by Django 5.1.7 on 2025-03-20 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_img', models.ImageField(upload_to='static/images/')),
                ('about_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_defined', 'Not defined')], default='not_defined', max_length=12)),
            ],
        ),
    ]
