# Generated by Django 5.1.7 on 2025-04-01 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0009_alter_movie_budget_alter_movie_overview_and_more'),
        ('profileapp', '0003_alter_profile_profile_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_status', models.CharField(choices=[('planned', 'Planned'), ('viewed', 'Viewed'), ('abandoned', 'Abandoned'), ('postponed', 'Postponed')], default='not_defined', max_length=12)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
