# Generated by Django 5.1.7 on 2025-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso_3166_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=100, unique=True)),
                ('native_name', models.CharField(max_length=100)),
            ],
        ),
    ]
