# Generated by Django 5.1.7 on 2025-03-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='english_name',
            field=models.CharField(max_length=100),
        ),
    ]
