# Generated by Django 5.1.7 on 2025-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_alter_language_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField()),
                ('revenue', models.PositiveBigIntegerField()),
                ('budget', models.PositiveBigIntegerField()),
                ('runtime', models.PositiveBigIntegerField()),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('genres', models.ManyToManyField(to='moviesapp.moviegenres')),
            ],
        ),
    ]
